### ISSUE TITLE
strictures and warnings

### ISSUE THREAD

**Issue by cowens** [CodeDmitry/NodePL#1]
In Perl 5, the strict and warnings pragmas are lexically scoped.  So, your modules (such as PLON.pm) should, at the very least, use strict and should probably use warnings as well.

**Comment by CodeDmitry** [comment]
I was afraid that require/use acts somewhat like "include in C", and by committing to require/use would bleed their strictness into global scope of the programs using it. 

Originally, I was considering dropping strict entirely to allow defining of "global" objects inside modules, but if I make a runtime that defined "my $global = {};" then the modules can hook to it, so there is no need to break strictness for that.

I modified it to put the strict and warnings in, removed code modifying global scope accidentally via $code variable thanks to the feedback from strict.
